### ISSUE TITLE
local.ERROR: Argument 1 passed to BeyondCode\LaravelWebSockets\Apps\App::findByKey() must be of the type string, null given - 1.11.0

### ISSUE THREAD

**Issue by lovetoast** [beyondcode/laravel-websockets#704] opened 2021-02-28 15:49 UTC
Hi, got the other error in the logs (when it is trying to insert statistics). 

Hardcoding the key in App.php solves this. Pusher driver is set in .env, but it appears that it is trying to pick up a key and it is getting null?

**Comment by simonbuehler** [comment] 2021-03-01 07:56
seems to be a duplicate of #700

**Comment by bbashy** [comment] 2021-03-01 19:29
Yep same.

**Comment by rennokki** [comment] 2021-03-02 17:52
I'll close this issue. See you in #700

**Closed by rennokki** 2021-03-02 17:52 UTC
