### ISSUE TITLE
Webosckets Promise Exception

### ISSUE THREAD

**Issue by FrWalou** [beyondcode/laravel-websockets#1139] opened 2023-07-18 13:05 UTC
Hello, my websocket is nicely running and i can broadcast events from Laravel through it and listen to it from front vueJS.
But since few days i'm facing some issue popping into my websocket cli, everything is working fine but i have this popping 
``
Unhandled promise rejection with TypeError: React\Http\Io\ClientRequestStream::closeError(): Argument #1 ($error) must be of type Exception, Error given, called in /var/www/html/vendor/react/promise/src/Internal/RejectedPromise.php on line 73 in /var/www/html/vendor/react/http/src/Io/ClientRequestStream.php:238
``

``
Unhandled promise rejection with RuntimeException: Request timed out after 60 seconds in /var/www/html/vendor/react/http/src/Io/Transaction.php:129
``

**Comment by sahramelissa** [comment] 2023-07-18 23:30
Hi everyone The problem is phpreact has a breaking change in their repos so "Unhandled promise rejection with TypeError" is **not** the exactly errors but yes there is a stackstrace. This won't be fixed soon after I track this issue.

**Comment by khoazero123** [comment] 2023-08-02 15:44
This work for me: `composer require react/promise:^2.3`

For details, check my comment in this issue: https://github.com/beyondcode/laravel-websockets/issues/1142#issuecomment-1662450503

**Comment by phpmac** [comment] 2023-09-03 17:28
look this 

https://github.com/beyondcode/laravel-websockets/issues/1158

you need install fix this error

```sh

composer require react/promise:^2.3


```

please close this,

**Comment by pajkho** [comment] 2023-09-12 16:07
@mpociot any ideas on this issue? using a lower version for react/promise works as a workaround but I assume that is not a permanent solution?

Or it should be added to the packages json file?

**Comment by Ragul-itsk** [comment] 2023-10-01 20:51
Check the BROADCAST_DRIVER=pusher in .env file, on "react/promise": "3.0" it's work fine. no need to make your version lower

**Comment by aldhinya** [comment] 2023-11-03 08:22
`composer require react/promise:^2.3`

worked for me xD

**Comment by NicolasMeseguer** [comment] 2023-12-05 02:48
Hi all, I'm new to Websockets, I just did a fresh installation of the Laravel Websockets with:
`composer require beyondcode/laravel-websockets`

After configuring everything and setting the path to access the dashboard, I started getting this weird error. I tried updating the react/promise as mentioned above:
`composer require react/promise:^2.3`

However, this is the output of the terminal:
```
PS C:\xampp\htdocs\websockets-test> composer require react/promise:^2.3
The "2.3" constraint for "react/promise" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Running composer update react/promise
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires react/promise 2.3 (exact version match: 2.3, 2.3.0 or 2.3.0.0), found react/promise[v2.3.0] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - react/dns v1.12.0 requires react/promise ^3.0 || ^2.7 || ^1.2.1 -> found react/promise[v1.2.1, v1.3.0, v2.7.0, ..., v2.11.0, v3.0.0, v3.1.0] but it conflicts with your root composer.json require (2.3).
    - beyondcode/laravel-websockets 1.14.1 requires react/dns ^1.1 -> satisfiable by react/dns[v1.12.0].
    - beyondcode/laravel-websockets is locked to version 1.14.1 and an update of this package was not requested.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Also tried with `-W` but got the same result, any idea how could I fix it ?
Thanks in advance,
Nico.

**Comment by Marwan1998** [comment] 2023-12-09 00:58
> Hi all, I'm new to Websockets, I just did a fresh installation of the Laravel Websockets (1.14.1) with: `composer require beyondcode/laravel-websockets`
> 
> After configuring everything and setting the path to access the dashboard, I started getting this weird error. I tried updating the react/promise as mentioned above: `composer require react/promise:^2.3`
> 
> However, this is the output of the terminal:
> 
> ```
> PS C:\xampp\htdocs\websockets-test> composer require react/promise:^2.3
> The "2.3" constraint for "react/promise" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
> ./composer.json has been updated
> Running composer update react/promise
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires react/promise 2.3 (exact version match: 2.3, 2.3.0 or 2.3.0.0), found react/promise[v2.3.0] but these were not loaded, likely because it conflicts with another require.
>   Problem 2
>     - react/dns v1.12.0 requires react/promise ^3.0 || ^2.7 || ^1.2.1 -> found react/promise[v1.2.1, v1.3.0, v2.7.0, ..., v2.11.0, v3.0.0, v3.1.0] but it conflicts with your root composer.json require (2.3).
>     - beyondcode/laravel-websockets 1.14.1 requires react/dns ^1.1 -> satisfiable by react/dns[v1.12.0].
>     - beyondcode/laravel-websockets is locked to version 1.14.1 and an update of this package was not requested.
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> ```
> 
> Also tried with `-W` but got the same result, any idea how could I fix it ? Thanks in advance, Nico.

Do this installation

`composer require react/promise:^2.3`
`composer update`

Then
`npm install`
`npm run dev`

The run dev is too important.

**Comment by Waleedx249i** [comment] 2023-12-11 13:14
that didn't work with me

**Comment by lyt8384** [comment] 2024-01-12 08:51
same ...

**Closed** 2024-02-07 17:31 UTC
