### ISSUE TITLE
Websockets not working with pusher-php-server 7.2

### ISSUE THREAD

**Issue by szabrzyski** [beyondcode/laravel-websockets#1041] opened 2022-10-05 22:31 UTC
Hello, after pusher-php-server has been updated to version 7.2 websockets stopped working. I'm using Laravel Echo and the initial connection to private channel is successful, but then I'm not getting any events broadcasted on that channel. With pusher-php-server 7.0.2 everything works fine. Is the new version incompatible with Laravel Websockets and should I wait for an update?

**Comment by dunakov** [comment] 2022-10-06 08:00
I also lowered version for stable work laravel-websockets)

**Comment by mankms** [comment] 2022-10-09 09:59
**Workaround**

```
composer require pusher/pusher-php-server:7.0.2
```

**Comment by Nielson** [comment] 2022-10-11 07:18
Holy shit. Thanks @szabrzyski ! I've been struggling with this for 1½ weeks now and couldn't figure out why my client side didn't catch the event.

**Comment by LipeApp** [comment] 2022-10-11 09:09
Когда планируется обновления? На 7.2 много чего который хотели бы пробовать.

**Comment by luceos** [comment] 2022-10-12 12:15
I have traced the issue to this: https://github.com/pusher/pusher-http-php/pull/329/files#r993378977

**Comment by madpilot78** [comment] 2022-10-13 21:13
Also experiencing this issue.

A bug report has been filed also at pusher/pusher-http-php#351

@luceos Strange, actually beyondcode/laravel-websockets does accept both channel and channels:

https://github.com/beyondcode/laravel-websockets/blob/1f25913ce05c66bbff1f925106bf9490ec0eb3bf/src/API/TriggerEvent.php#L21

Have you actually tested a patch that solves the issue?

**Comment by luceos** [comment] 2022-10-14 06:39
I don't know then @madpilot78; truth be told I have a fork because I needed a custom implementation. And in this fork it now works. Diffing the last version with the new one, and testing things locally, only the channel change has been the most apparent one. 

The code you mentioned, which correctly adds the ability to read `channel` if it is set, was only merged into master 8 days ago, whereas the last release is from March for 1.x.

**Comment by madpilot78** [comment] 2022-10-14 07:41
> I don't know then @madpilot78; truth be told I have a fork because I needed a custom implementation for a @flarum extension. And in this fork it now works. Diffing the last version with the new one, and testing things locally, only the channel change has been the most apparent one.

No you're probably right, I'm going to test again.

> 
> The code you mentioned, which correctly adds the ability to read `channel` if it is set, was only merged into master 8 days ago, whereas the last release is from March for 1.x. I assume that's the culprit, these changes haven't been released yet and so any published version of this package will still only allow `channels` in the payload.

Oh, sorry, my bad I did not check when it was added. Then I'll test using code with that addition, maybe forcing using the repo head.

**Comment by madpilot78** [comment] 2022-10-14 12:00
I've tested and filed pull request #1046 against branch 1.x that should fix the issue.

Thanks to @luceos for pointing me in the right direction.

**Comment by vnestoruk** [comment] 2022-10-18 09:00
Two days that will never come back 😓 Thanks guys, at least you saved my nerves 🫡

**Comment by tomvo** [comment] 2022-10-19 07:59
thanks @madpilot78 for fixing this, we're currently struggling with this issue on production. Any timeline on when this will be merged and tagged?

**Comment by octhavio** [comment] 2022-10-25 13:49
> composer require pusher/pusher-php-server:7.0.2

Thank you so much! I've been stuck on this issue for days. You are my hero. I consider you from now on one of my closest friends. We're practically family now.

**Comment by gavinsbtm** [comment] 2022-10-26 22:59
2 days of my life wasted... Thank god I found this page before the weekend.

Thanks to [Bvanhaastrecht](https://laracasts.com/@Bvanhaastrecht)

**Comment by vutungf** [comment] 2022-10-27 07:53
> 2 days of my life wasted... Thank god I found this page before the weekend.

me too 👍

**Comment by bci24** [comment] 2022-10-27 09:07
in laravel 9.37 with laravel-websockets 1.13.1 the solutions was downgrading to pusher-php-server 7.0.2 **or** use the latest pusher-php-server 7.2.1 and manually patch the TriggerEventController from here https://github.com/beyondcode/laravel-websockets/pull/1046/commits/fe78daf914aa5a60d47402b2d0b6390e83c9102a

**Comment by tomvo** [comment] 2022-10-27 10:42
@bci24 a better fix would be to use `"beyondcode/laravel-websockets": "1.x-dev",` in your composer instead of manually patching stuff.

**Comment by jafar690** [comment] 2022-10-29 18:00
Spent 4 hours debugging the same issue, 4 hours i won't get back. thanks @mankms

**Comment by medilies** [comment] 2022-10-29 21:50
Spent the whole day editing configs and changing the composer file to figure out that V7.2 is broken is the source of the problem https://github.com/medilies/trying-laravel-websockets/compare/6f60c31...a5223dd

**Comment by lordjoo** [comment] 2022-10-30 13:10
I've downgrade the pusher-php-server and still the client doesn't catch the events abd in the dashboard they didn't appear too

**Comment by lordjoo** [comment] 2022-10-30 13:16
I've ended up switching to soketi

**Comment by kamilkahar90** [comment] 2022-10-30 17:24
Looking forward to this issue being resolved. Downgrade pusher-php-server to 7.0.2 working for me.

**Comment by MellianStudios** [comment] 2022-11-05 10:51
what version of echo and pucherjs are you using ? i downgraded to 7.0.2 and now instead of no data i get 
`
Firefox can’t establish a connection to the server at ws://127.0.0.1:6001/app/key?protocol=7&client=js&version=7.4.0&flash=false.
The connection to ws://127.0.0.1:6001/app/key?protocol=7&client=js&version=7.4.0&flash=false was interrupted while the page was loading.
`

**Comment by Steffra** [comment] 2022-11-05 19:01
Unfortunately i've only found this issue after i've already resolved it by myself. Downgrading to 7.0.2 is the only thing that has worked for me.
Can't wait untill it's fixed!

**Comment by DanJamesMills** [comment] 2022-11-08 18:11
I had the same issue guys been debugging until this afternoon to find this thread

**Comment by kluevandrew** [comment] 2022-11-12 23:22
A best way to fix:

`./vendor/beyondcode/laravel-websockets/src/HttpApi/Controllers/TriggerEventController.php`

```php
<?php

namespace BeyondCode\LaravelWebSockets\HttpApi\Controllers;

use BeyondCode\LaravelWebSockets\Dashboard\DashboardLogger;
use BeyondCode\LaravelWebSockets\Facades\StatisticsLogger;
use Illuminate\Http\Request;

class TriggerEventController extends Controller
{
    public function __invoke(Request $request)
    {
        $this->ensureValidSignature($request);

        $channels = $request->json()->get('channels', []);
        $channel = $request->json()->get('channel');
        if ($channel) {
            $channels[] = $channel;
        }
        foreach ($channels as $channelName) {
            $channel = $this->channelManager->find($request->appId, $channelName);

            optional($channel)->broadcastToEveryoneExcept([
                'channel' => $channelName,
                'event' => $request->json()->get('name'),
                'data' => $request->json()->get('data'),
            ], $request->json()->get('socket_id'));

            DashboardLogger::apiMessage(
                $request->appId,
                $channelName,
                $request->json()->get('name'),
                $request->json()->get('data')
            );

            StatisticsLogger::apiMessage($request->appId);
        }

        return (object) [];
    }
}
```

**Comment by madpilot78** [comment] 2022-11-13 17:24
> A best way to fix:
> 
> `./vendor/beyondcode/laravel-websockets/src/HttpApi/Controllers/TriggerEventController.php`
[...]

@kluevandrew You suggested patch looks very similar to mine from #1046, which has already been merged to the 1.x branch.

Unluckily until a new release is cut from 1.x the change is not going to be distributed automatically.

Let's hope a new 1.x release is cut soon.

**Comment by AliKhedmati** [comment] 2022-11-14 13:21
I still had the issue with v7.2.1
Downgrading to v7.0.2 was working fine for me.

**Comment by madpilot78** [comment] 2022-11-14 14:50
@AliKhedmati

The issue is in beyondcode/laravel-websockets. `pusher/pusher-http-php` has changed how it accesses its own API and is not going back, they have no reason too, they do not support servers except their own.

`beyondcode/laravel-websockets` needs to adapt to the new way the client accesses the API.

**Comment by tomvo** [comment] 2022-11-29 05:35
I don't understand why the fix is merged but not a new release being tagged. Is this repo even maintained? @mpociot

**Comment by Msangi21** [comment] 2022-11-30 08:55
> **Workaround**
> 
> ```
> composer require pusher/pusher-php-server:7.0.2
> ```

You saved my 3 days

**Closed** 2022-12-14 08:58 UTC

**Comment by 099912** [comment] 2023-08-09 17:41
"php": "^8.0",
        "beyondcode/laravel-websockets": "^2.0@beta",
        "cboden/ratchet": "^0.4.4",
        "cviebrock/eloquent-sluggable": "^9.0",
        "fruitcake/laravel-cors": "^2.0.5",
        "guzzlehttp/guzzle": "^7.7",
        "illuminate/session": "*",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.7",
        "pusher/pusher-php-server": "7.0.2", 
        I have this version of laravel i think beta 2.o websockets doesnot work for php 8 I also downgrade the pusher from 7.2 to 7.0 but the dashboard of websocj=ket doesnot catch the event

**Comment by jdthehelper** [comment] 2024-01-23 05:22
I have create full documentation for laravel websocket with realted issue every time. Please check it https://myphpinformation.blogspot.com/2024/01/laravel-websocket-setup-and-example-how-to-use-it.html this my help you.
