### ISSUE TITLE
validate_channels(): Argument #1 ($channels) must be of type array, Collection given

### ISSUE THREAD

**Issue by butaminas** [beyondcode/laravel-websockets#981] opened 2022-05-09 13:00 UTC
Everything was working fine for a long time until now. I started to get this error out of nowhere:
`Pusher\\Pusher::validate_channels(): Argument #1 ($channels) must be of type array, Illuminate\\Support\\Collection given, called in /vendor/pusher/pusher-php-server/src/Pusher.php on line 341`

The error occurs when trying to broadcast an event like so:
`broadcast(new UpdateListEvent());`

Using `Laravel 9` and `laravel-webscokets 1.13.1`

Any ideas?

---
**Update 1:**
Figured out that it was a particular composer update that caused this issue and the update was to the main Laravel package:
`laravel/framework (9.x-dev 3be7023 => 9.x-dev c51ef98)`
After update to `9.x-dev c51ef98` it stops working. I think the issue is with `Laravel` it self and not `laravel-websockets`

**Comment by lucasvscn** [comment] 2022-05-10 19:20
It seems the error is caused by Laravel 9.12.0 with Pusher 7.0. I've just opened this [PR](https://github.com/laravel/framework/pull/42340) on Laravel repository.

**Comment by camiant** [comment] 2022-05-12 07:51
same here

**Comment by mikebronner** [comment] 2022-05-12 13:44
A fix has been released in [Laravel](https://github.com/laravel/framework/releases). If you had already installed version 9.12.0 in the past, try this:
1. Revert to 9.11, and run composer update.
2. Clear composer cache: `composer clear-cache`
3. Change Laravel framework version back to `^9.12` and run composer update. You should name have the version with the fix in it.

The likely problem is that they deleted the bad 9.12.0 release, made a fix, then re-released it as 9.12.0.

**Comment by lucasvscn** [comment] 2022-05-12 17:10
hi @mikebronner the fix was tagged as [9.12.1](https://github.com/laravel/framework/commits/v9.12.1)

so you can just update your project with `composer update` and it will be working again.

**Comment by Messhias** [comment] 2022-05-12 20:12
I believe this issue can be closed since it was a Laravel issue.

**Closed** 2022-06-06 10:43 UTC
