### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by tzer-kee** [beyondcode/laravel-websockets#852] opened 2021-09-14 01:20 UTC
The Laravel framework version I used is 8.60.0 with PHP version 7.3.12. I want to use this package for my live auction system, however, there is a lot of problems installing this package. 

This is what I get when I run `composer require beyondcode / laravel-websockets`

![image](https://user-images.githubusercontent.com/89755166/133178491-dfaa2ab0-d5b4-40a5-b833-bf1c341a1a6b.png)

Then I run `composer require beyondcode / laravel-websockets --with-all-dependencies`, more problems occur.

![image](https://user-images.githubusercontent.com/89755166/133178277-325b4074-3611-4ef1-83a3-dd412cd190d2.png)

Can someone provide a working instruction for installing laravel-websockets on laravel v8.x? Or does it really work in the latest laravel version?

Thank you in advance!

**Comment by tibbsa** [comment] 2021-09-15 17:53
Duplicate of / see https://github.com/beyondcode/laravel-websockets/issues/784 for a potential resolution. (The question will be whether the forced downgrade of `guzzlehttp/psr7` causes problems elsewhere.)

**Closed** 2024-02-07 17:33 UTC
