### ISSUE TITLE
StatisticsUpdated job crashing

### ISSUE THREAD

**Issue by ohnotnow** [beyondcode/laravel-websockets#10] opened 2018-12-05 09:26 UTC
I've gone through the install and things seem to be working great as a drop-in replacement for Pusher - thanks! This is way nicer to use than the node echo server! :-)

I do keep seing a failed job in the horizon queue runner though - and no stats are being gathered (but the notifications are coming through ok in the app).  The queue runner is outputting :

```
[2018-12-05 09:15:50][199] Processing: BeyondCode\LaravelWebsockets\Statistics\Events\StatisticsUpdated

   Symfony\Component\Debug\Exception\FatalErrorException  : method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "BeyondCode\LaravelWebsockets\Statistics\Events\StatisticsUpdated" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition

  at /Users/ohffs/Documents/code/examdb/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php:43
    39|      * @return void
    40|      */
    41|     public function handle(Broadcaster $broadcaster)
    42|     {
  > 43|         $name = method_exists($this->event, 'broadcastAs')
    44|                 ? $this->event->broadcastAs() : get_class($this->event);
    45|
    46|         $broadcaster->broadcast(
    47|             Arr::wrap($this->event->broadcastOn()), $name,


   Whoops\Exception\ErrorException  : method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "BeyondCode\LaravelWebsockets\Statistics\Events\StatisticsUpdated" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition

  at /Users/ohffs/Documents/code/examdb/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php:43
    39|      * @return void
    40|      */
    41|     public function handle(Broadcaster $broadcaster)
    42|     {
  > 43|         $name = method_exists($this->event, 'broadcastAs')
    44|                 ? $this->event->broadcastAs() : get_class($this->event);
    45|
    46|         $broadcaster->broadcast(
    47|             Arr::wrap($this->event->broadcastOn()), $name,

PHP Fatal error:  method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "BeyondCode\LaravelWebsockets\Statistics\Events\StatisticsUpdated" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /Users/ohffs/Documents/code/examdb/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php on line 43
```

I'm using redis as the queue driver.  I've tried the usual dump-autoload etc, restarting everything - but it keeps happening.  I had a look at the StatisticsUpdated class and nothing was leaping out at me as being the 'ah-ha!' problem - sorry :-/

**Comment by mpociot** [comment] 2018-12-05 09:32
Have you restarted the queue worker so that it knows about the new event?
That's the only thing that comes to mind right now :)

**Comment by ohnotnow** [comment] 2018-12-05 09:37
Yep - been stopping and starting it quite a bit to try and debug it myself :-)  I'll keep poking at it - if I find the reason I'll post back here :-) 

Thanks again for the package - it's very appreciated :-)

**Comment by stayallive** [comment] 2018-12-06 14:56
Same here, maybe this Sentry event helps somehow: https://sentry.io/share/issue/ca6da1cdacaa4b179bd943dcb128cd44/

**Comment by irazasyed** [comment] 2018-12-06 20:04
The issue should be fixed with the PR #33.

I'm testing since last few hours and it seems to be fine now.

**Comment by mpociot** [comment] 2018-12-06 20:43
This is now fixed with 1.0.2

**Closed by mpociot** 2018-12-06 20:43 UTC

**Comment by google-mac** [comment] 2019-02-06 16:56
I am having this same issue and I am on v1.0.4. I receive it when I run `php artisan queue:work` with the database as the queue connection.

**Comment by Slawe** [comment] 2019-02-13 16:04
just delete that event from "jobs" table in database.

**Comment by akkhan20** [comment] 2019-02-16 15:19
Same issue queue worker crashing, everything was working fine but i installed laravel-websockets in a separate project and configured broadcast driver as 'pusher' and added the host and port in my existing project and now the queue worker is crashing.

**Comment by akkhan20** [comment] 2019-02-16 15:28
The app names are different on both the projects though so:
`'prefix' => env('CACHE_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_cache'),`
should not allow the cache clash.

**Comment by akkhan20** [comment] 2019-02-16 15:42
Separating the cache dbs solved it, add unique db in both the projects, the issue is not related to this project
`REDIS_DB=2`
`REDIS_CACHE_DB=2`
