### ISSUE TITLE
Using custom and default handlers together

### ISSUE THREAD

**Issue by matheusb-comp** [beyondcode/laravel-websockets#309] opened 2020-01-30 04:01 UTC
After reading the [Custom WebSocket Handlers](https://docs.beyondco.de/laravel-websockets/1.0/advanced-usage/custom-websocket-handlers.html) documentation and the [Router](https://github.com/beyondcode/laravel-websockets/blob/master/src/Server/Router.php) code, I understood that by using `WebSocketsRouter::webSocket()` a new websocket endpoint is [added](https://github.com/beyondcode/laravel-websockets/blob/master/src/Server/Router.php#L83) to the server, that still keeps the default `/app/{appKey}` route (compliant with the Pusher protocol).

Then, after setting my custom handler endpoint in `routes/web.php`:
```
WebSocketsRouter::webSocket('/test', \App\SimpleWebsocketHandler::class);
```
That just logs that the connection happened:
```
class SimpleWebsocketHandler implements MessageComponentInterface
{
    public function onOpen(ConnectionInterface $connection) { Log::info('onOpen'); }
    ...
```
I can verify that the server has both the `/app/{appKey}` and `/test` endpoints.

However, when the Laravel Echo instance in the browser tries to connect using the default route:
```
GET ws://localhost:6001/app/816622f4d65f3c4e1d2e11011658b785?protocol=7&client=js&version=5.0.3&flash=false
```
The custom `onOpen` function is executed instead:
```
Starting the WebSocket server on port 6001...
New connection opened for app key 816622f4d65f3c4e1d2e11011658b785.
[2020-01-30 00:30:51] local.DEBUG: onOpen  
Connection id  closed.
```
And since the custom handler doesn't [establish the connection](https://github.com/beyondcode/laravel-websockets/blob/master/src/WebSockets/WebSocketHandler.php#L35) and nothing is returned to the browser, the Laravel Echo connection fails with the error:
```
app.js:1 WebSocket connection to 'wss://localhost/app/816622f4d65f3c4e1d2e11011658b785?protocol=7&client=js&version=5.0.3&flash=false' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

So, is my understanding wrong? Is it not possible to use both a custom handler and the default Pusher compliant handler together?

In the issue [#21](https://github.com/beyondcode/laravel-websockets/issues/21#issuecomment-538328288) the example provided is a child of the default `WebSocketHandler`, but then when calling the `parent::onOpen()`, the Pusher format will be expected.

**Comment by matheusb-comp** [comment] 2020-01-31 03:40
Interestingly, when setting [`APP_DEBUG=false`](https://github.com/beyondcode/laravel-websockets/issues/296) on `.env`, it works.
The default endpoint allows pusher-js to connect, and the custom handler receives bare-bones websocket connections, just as expected.

So, the problem is in the [Logger](https://github.com/beyondcode/laravel-websockets/blob/master/src/Server/Logger/Logger.php)? I could not understand how the code works.

**Comment by rennokki** [comment] 2020-08-13 09:46
Duplicate of https://github.com/beyondcode/laravel-websockets/issues/296

**Closed by rennokki** 2020-08-13 09:46 UTC
