### ISSUE TITLE
does it work in laravel 8 and php 8?

### ISSUE THREAD

**Issue by maritojhefi** [beyondcode/laravel-websockets#838] opened 2021-08-23 06:02 UTC
I am trying to implement websockets in a laravel 8 project but I have several drawbacks

**Comment by michelvambattu** [comment] 2021-08-25 08:20
It works. Could you explain the issue?

**Comment by sreerajlal** [comment] 2021-08-28 10:07
No it will not work. Will get an error Channels current state is unavailable.

**Comment by another-universe** [comment] 2021-08-30 22:09
I subscribe to the question.
This is a really great package. I have used it in several of my projects.
But now I have problems installing laravel-websockets on laravel latest version.


This is what I get when I run `composer require beyondcode / laravel-websockets`:
```bash
Using version ^1.12 for beyondcode/laravel-websockets
./composer.json has been updated
Running composer update beyondcode/laravel-websockets
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```


Let's try with the `--with-all-dependencies` option:
```bash
Using version ^1.12 for beyondcode/laravel-websockets
./composer.json has been updated
Running composer update beyondcode/laravel-websockets --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^8.54, found laravel/framework[v8.54.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```


Ok, let's try to install the second version. Although it is still in beta.
```bash
./composer.json has been updated
Running composer update beyondcode/laravel-websockets
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beyondcode/laravel-websockets[2.0.0-beta.28, ..., 2.x-dev] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - beyondcode/laravel-websockets[2.0.0-beta.1, ..., 2.0.0-beta.29] require php ^7.2 -> your php version (8.0.10) does not satisfy that requirement.
    - Root composer.json requires beyondcode/laravel-websockets ^2.0 -> satisfiable by beyondcode/laravel-websockets[2.0.0-beta.1, ..., 2.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```


And now with the `--with-all-dependencies` option:
```bash
./composer.json has been updated
Running composer update beyondcode/laravel-websockets --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^8.54, found laravel/framework[v8.54.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```


As you can see, the situation has not changed at all.

I already wrote that I really like this package, but why is it so difficult to install it?
You need to be more flexible in dealing with dependencies.

Can someone provide a working instruction for installing laravel-websockets on laravel v8.x + php v8.x?

Thanks!

**Comment by singhsanjay5151** [comment] 2021-09-03 12:33
@maritojhefi @sreerajlal @another-universe 
have anyone got success in laravel 8

i am tring to install  beyondcode / laravel-websockets-demo but getting error 

D:\xampp\htdocs\laravel-websockets-chat>composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.1.3 but your php version (8.0.9) does not satisfy that requirement.
  Problem 2
    - laravel/framework[v5.7.0, ..., 5.7.x-dev] require php ^7.1.3 -> your php version (8.0.9) does not satisfy that requirement.
    - Root composer.json requires laravel/framework 5.7.* -> satisfiable by laravel/framework[v5.7.0, ..., 5.7.x-dev].


please reply

**Comment by another-universe** [comment] 2021-09-03 19:25
@singhsanjay5151
Yes, I managed to install it.
I have installed beyondcode/laravel-websockets v2 on laravel v8.
```bash
composer require -w "beyondcode/laravel-websockets:^2.0"
```
Please note that in this case the guzzlehttp / psr7 version will be downgraded to 1.8.2.
Also, if you are using the doctrine/dbal v3.x package, it will also be downgraded to 2.13.2.
Otherwise, I have not noticed any unwanted side effects.
By the way, I checked that beyondcode/laravel-websockets v1.x is also installed in the same way.
But personally, I decided to stay on version 2, despite the fact that version 2 is still in beta. At least I have no complaints about the functioning at the moment.

**Comment by AlexioVay** [comment] 2021-09-08 18:58
Is this even still maintained? There are 111+ issues right now. I'm using Laravel Jetstream with Livewire.

**Comment by arbiyanto** [comment] 2021-09-08 19:44
Honestly, it's really painful for me after worked 3 hours but still failed to solve the problems when using this package with the latest Laravel version.

In the end, I ended up using [Laravel Echo Server](https://github.com/tlaverdure/laravel-echo-server), and pulling the [docker image](https://github.com/oanhnn/docker-laravel-echo-server), just configure a little bit then it's running without any issue. Not a great idea, but it works more for my case. Although I'm not really sure if there's any trade-off.

**Comment by tibbsa** [comment] 2021-09-15 17:54
Duplicate of / see https://github.com/beyondcode/laravel-websockets/issues/784 for a potential resolution. (The question will be whether the forced downgrade of `guzzlehttp/psr7` causes problems elsewhere.)

**Comment by mondwan** [comment] 2021-09-25 07:50
> Problem 1
> - Root composer.json requires php ^7.1.3 but your php version (8.0.9) does not satisfy that requirement.
> Problem 2
> - laravel/framework[v5.7.0, ..., 5.7.x-dev] require php ^7.1.3 -> your php version (8.0.9) does not satisfy that requirement.
> - Root composer.json requires laravel/framework 5.7.* -> satisfiable by laravel/framework[v5.7.0, ..., 5.7.x-dev].

IMO, the errors are pretty clear?

* You are using php8 while that project, you are quoting, requires php 7.1.X.
* 2ndly, you claim that you are going to test laravel 8 but you r using `laravel-framework 5.x`?

**Comment by m33ts4k0z** [comment] 2021-10-19 05:28
Hello,

Laravel 8 and websockets v1 works pretty well but indeed a downgrade of some packages is needed.

Deleting the composer.lock and running the following command will make websockets work correctly in Laravel 8:

`composer require -W beyondcode/laravel-websockets`

However do note that if you will be doing this in an already started project, there are chances that you will break something by forcing a package downgrade.

**Comment by mcribz** [comment] 2022-02-25 11:50
hello is not workng help

**Closed** 2024-02-07 17:33 UTC
